name: Generate doxygen docs and deploy to github pages

on:
  push

jobs:

  gen_docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Generate docs
      uses: mattnotmitt/doxygen-action@v1.9.5
      with:
        doxyfile-path: 'Doxyfile'


    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y graphviz
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./html  # Set this to the Doxygen output directory
        keep_files: false  # Set to true to keep files that are not in the Doxygen output directory